apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ios-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-ios-app
  template:
    metadata:
      labels:
        app: react-ios-app
    spec:
      containers:
        - name: react-ios-app
          image: babu120987/react-ios-calculator:latest
          ports:
            - containerPort: 80
