apiVersion: v1
kind: Service
metadata:
  name: react-ios-calculator-svc
spec:
  type: NodePort
  selector:
    app: react-ios-calculator
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090
